

#INCLUDE "rwmake.ch"
#INCLUDE "topconn.ch"

//------------------------------------------------------------------------------------
/*{Protheus.doc}ADV001
Rotina para montagem de tela de TIPOS DE CHAMADOS do Axcadastros

@author Marcos Silvestrini
@version P12
@since
*/
//------------------------------------------------------------------------------------
User Function ADV003()

AxCadastro("ZZC","Cadastro de Tipos de Chamados")

Return
