
#INCLUDE "rwmake.ch"
#INCLUDE "topconn.ch"

//------------------------------------------------------------------------------------
/*{Protheus.doc}ADV001
Rotina para montagem de tela de SLA do Axcadastros

@author Marcos Silvestrini
@version P12
@since
*/
//------------------------------------------------------------------------------------
User Function ADV002()

AxCadastro("ZZB","Cadastro de SLA")

Return
