

#INCLUDE "rwmake.ch"
#INCLUDE "topconn.ch"

//------------------------------------------------------------------------------------
/*{Protheus.doc}ADV001
Rotina para montagem de tela de CADASTRO DE CHAMADOS do Axcadastros

@author Marcos Silvestrini
@version P12
@since
*/
//------------------------------------------------------------------------------------
User Function ADV004()

AxCadastro("ZZD","Cadastro de Chamados")

Return

