#INCLUDE "rwmake.ch"
#INCLUDE "topconn.ch"

//------------------------------------------------------------------------------------
/*{Protheus.doc}axCadastros
Rotina para montagem de tela de tecnico do Axcadastros

@author Marcos Silvestrini
@version P12
@since
*/
//------------------------------------------------------------------------------------
User Function ADV001()

AxCadastro("ZZA","Cadastro de Tecnicos")

Return
